### ISSUE TITLE
Использовать шаблон

### ISSUE THREAD

**Issue by lukasvs** [Niklan/Trash#2]
Я думаю, для этого тоже можно использовать шаблон, например так:

{% if $PRESET == Drupal_8 or $PRESET == Drupal_8_sub_domains %}
	set $root_path {% $VIRTUAL_DOCROOT %}/web;
{% else %}
    set $root_path {% $VIRTUAL_DOCROOT %};
{% endif %}

Также будьте осторожны, у них этот шаблонизатор, как показала моя практика очень сырой. Где-то пол года назад выяснил, что у них неверно работала операция "неравно", обещали поправить )

**Comment by Niklan** [comment]
@lukasvs о! он поддерживает или, найс. А строки как им проверять?

У меня он даже не понимает `$PRESET == 'Drupal 8'`, или же `$PRESET == "Drupal 8"`. Вообще он странный какой-то. Где про возможности шаблонизатора почитать? Даже в [оф. документации](https://docs.ispsystem.ru/ispmanager-lite/nastrojki-veb-serverov/shablonizator-konfiguratsionnyh-fajlov) ни слова про то что он умеет в `or` или `and`, меня это даже озадачило. Как он со строками работает и т.д.

Это их собственный или какой-то внешний шаблонизатор? Вообще документация скудненькая какая-то.

По поводу предложения. Не понял зачем

```
 if $PRESET == Drupal_8 or $PRESET == Drupal_8_sub_domains %}
set $root_path {% $VIRTUAL_DOCROOT %}/web;
{% else %}
set $root_path {% $VIRTUAL_DOCROOT %};
{% endif %}
```

Ведь то что корень в web, можно прямо в админке домена указать. Не думаю что тут имеет смысл костылить на уровне конфигов, а лучше явно указать у домена где у него докрут. Это у весты таких возможностей нет и приходилось 100500 конфигов  на каждый вариант делать. Тут как-то поумнее подошли к ним, но всеравно странно.

Почему бы просто не сделать шаблоны с выбором для домена, а не шаблоны юзера, которые распространяются на все домены и под каждый пилить nginx конфиг как-то странно.

**Comment by lukasvs** [comment]
Узнал про шаблоны, посмотрев их вебинар, сейчас нашёл только вот эту запись:
https://www.youtube.com/watch?v=0DaxzC9XGJQ&t=565s
Но если это и он, то очень сильно обрезанный, потому как там нет вопросов от смотрящих.
Вот там я задавал вопрос, на чём написан их шаблонизатор, саркостическим комментарием "twig"?
На это ведущая ответила: "Это наша собственная разработака".
Документации кроме этой не видел:

https://doc.ispsystem.ru/index.php/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80_%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D1%85_%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2

Когда столкнулся с проблемой, что не работает != написал им в поддержку и проблему подтвердили. Перед этим долго общался с девушкой в чате, которая не хотела вникать, и говорила, что шаблонизатор - это не их разработка, а какой-то язык, пока я не ткунл её в вебинар, где говорили об обратном. Как на самом деле так и не выяснили.

Ещё заметил, что комментарии в шаблоне нужно писать с осторожностью, уже не помню в чём дело, но какой-то косяк тоже есть, помоему их можно только в новой строке писать, а не в той же где уже написан код.

В общем такие вот дела )) Но в целом неплохо если много сайтов на серваке с разными системами - удобно управлять

**Comment by Niklan** [comment]
Сделал как они в вебинаре говорят: https://github.com/Niklan/Trash/blob/master/ISPManager/drupal-nginx.md

Только почему-то значение по умолчанию не восстанавливается. Но работает. И это мне больше нравится, нежели чем на шаблон юзеров опираться.

![image](https://user-images.githubusercontent.com/2356744/51035819-18cbd000-15cd-11e9-86a6-cf832bbcfac7.png)

**Comment by lukasvs** [comment]
Я смотрел, такой поход мне тоже больше понравился, но сам не пробовал.

**Comment by Niklan** [comment]
@lukasvs ну вот я щас попробовал. Всё работает. Гайд сразу собрал как делал.

Но не понял, почему значение по умолчанию то не восстанавливается. =\ Каждый раз при редактировании надо не забыть эту галку ткнуть.

**Comment by lukasvs** [comment]
Сейчас протестировал твой код у себя, такая же проблема, возможно баг какой-то, стоит написать в поддержку. Хотя там им сложно что-то доказать.

**Comment by Niklan** [comment]
https://github.com/Niklan/Trash/blob/master/ISPManager/nginx/drupal-nginx.md

В общем поддержка направла на доки о том как сохранять настройки. Инструкции дополнил. Теперь всё хранится как надо.

**Comment by lukasvs** [comment]
Спасибо, надо будет попробовать сделать по такому подходу.
